# -*- coding: utf-8 -*-
"""pyExp2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lxd7yWZp9Koay7QR_uXmu77hLq9-QulX
"""

class File:
    def __init__ (self, filename, method):
        self.file = open (filename, method)

    def __enter__ (self):
        print ('Enter Method is executed')
        return self.file

    def __exit__ (self, type, value, traceback):
        print (f'{type}, {value}, {traceback}')
        print ('Exit method is executed')
        self.file.close ()
        # return True
        if type == Exception:
            return True

if __name__ == '__main__':
    with File ('./Text.txt', 'r') as f:
        print ('Middle part is executed')
        print(f.read())
        raise Exception ()

class File:
    def __init__ (self, filename, method):
        self.file = open (filename, method)

    def __enter__ (self):
        print ('Enter Method is executed')
        return self.file

    def __exit__ (self, type, value, traceback):
        print (f'{type}, {value}, {traceback}')
        print ('Exit method is executed')
        self.file.close ()
        # return True
        if type == Exception:
            return True

if __name__ == '__main__':
    with File ('./Text.txt', 'a') as f:
        print ('Middle part is executed')
        f.write ('\n Helloo')
        raise Exception ()

class File:
    def __init__ (self, filename, method):
        self.file = open (filename, method)

    def __enter__ (self):
        print ('Enter Method is executed')
        return self.file

    def __exit__ (self, type, value, traceback):
        print (f'{type}, {value}, {traceback}')
        print ('Exit method is executed')
        self.file.close ()
        # return True
        if type == Exception:
            return True

if __name__ == '__main__':
    with File ('./Text.txt', 'r') as f:
        print ('Middle part is executed')
        print(f.read())
        raise Exception ()

class File:
    def __init__ (self, filename, method):
        self.file = open (filename, method)

    def __enter__ (self):
        print ('Enter Method is executed')
        return self.file

    def __exit__ (self, type, value, traceback):
        print (f'{type}, {value}, {traceback}')
        print ('Exit method is executed')
        self.file.close ()
        # return True
        if type == Exception:
            return True

if __name__ == '__main__':
    with File ('./Text.txt', 'w') as f:
        print ('Middle part is executed')
        f.write ('\n Bye')
        raise Exception ()

class File:
    def __init__ (self, filename, method):
        self.file = open (filename, method)

    def __enter__ (self):
        print ('Enter Method is executed')
        return self.file

    def __exit__ (self, type, value, traceback):
        print (f'{type}, {value}, {traceback}')
        print ('Exit method is executed')
        self.file.close ()
        # return True
        if type == Exception:
            return True

if __name__ == '__main__':
    with File ('./Text.txt', 'r') as f:
        print ('Middle part is executed')
        print(f.read())
        raise Exception ()